spring.application.name=jwt
# Configuração do Servidor
server.port=8181

# Configuração da Base de Dados H2 em Memória
spring.datasource.url=jdbc:h2:mem:productdb
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=

# Habilitar a Consola H2 para Acesso no Navegador
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

# Configuração do JPA / Hibernate
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# Ativar Perfil Ativo (conforme mencionado no guia para carga de dados)
spring.profiles.active=test

# Configurações do JWT
api.security.token.secret=MinhaChaveSuperSecretaECompridaParaAssinarOTokenJWT123456
api.security.token.expiration-ms=86400000